### ISSUE TITLE
Test ignore_malformed with latest ES snapshot

### ISSUE THREAD

**Issue by felixbarny** [gsantoro/es_tests#1]
Also, add ES version to reports so that we can compare the diff between versions more easily.

We're expecting to see a change in the ignore_malformed support for the boolean field type.
* https://github.com/elastic/elasticsearch/pull/93239

**Comment by gsantoro** [comment]
I am thinking of adding a new functionality that will enable to display a diff between 2 different runs of the reports. Currently it's quite hard on the eye to diff 2 reports.

**Comment by gsantoro** [comment]
I have created a PR at https://github.com/gsantoro/es_tests/pull/2. @felixbarny can you have a quick look?

**Comment by gsantoro** [comment]
Sorry I merged my own PR. I think the most important think is the report results. I'm happy to have a chat about this if necessary
